# Copyright (c) 2020 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

---
- name: Network Discovery (IOS)
  hosts: ios
  gather_facts: False
  tasks:
    - name: Importing Discovery commands
      include_vars:
        file: commands.yaml
        name: discovery_commands

    - name: Gather facts
      ios_facts:
        gather_subset: all
        gather_network_resources: all

    - name: Collect output from Discovery commands
      ios_command:
        commands: "{{ item }}"
      register: manual_discovery_commands
      with_items: "{{ discovery_commands.ios }}"
      ignore_errors: yes
  
    - name: Backup Configuration
      ios_config:
        backup: yes
        backup_options:
          dir_path: "./output/configs/"
          filename: "{{ inventory_hostname }}.txt"
  
- name: Network Discovery (IOS-XR)
  hosts: iosxr
  gather_facts: False
  tasks:
    - name: Importing Discovery commands
      include_vars:
        file: commands.yaml
        name: discovery_commands

    - name: Gather facts
      iosxr_facts:
        gather_subset: all
        gather_network_resources: all

    - name: Collect output from Discovery commands
      iosxr_command:
        commands: "{{ item }}"
      register: manual_discovery_commands
      with_items: "{{ discovery_commands.iosxr }}"
      ignore_errors: yes
  
    - name: Backup Configuration
      iosxr_config:
        backup: yes
        backup_options:
          dir_path: "./output/configs/"
          filename: "{{ inventory_hostname }}.txt"
        
- name: Network Discovery (NX-OS)
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Importing Discovery commands
      include_vars:
        file: commands.yaml
        name: discovery_commands

    - name: Gather facts
      nxos_facts:
        gather_subset: all
        gather_network_resources: all
    
    - name: Collect output from Discovery commands
      nxos_command:
        commands: "{{ item }}"
      register: manual_discovery_commands
      with_items: "{{ discovery_commands.nxos }}"
      ignore_errors: yes
    
    - name: Backup Configuration
      nxos_config:
        backup: yes
        backup_options:
          dir_path: "{{ output_directory }}/configs/"
          filename: "{{ inventory_hostname }}.txt"

- name: Write discovered information to disk
  hosts: all
  gather_facts: False
  tasks:
    - name: Write Device Facts
      copy:
        content: |
          {{ hostvars | to_nice_json }}
        dest: "{{ output_directory }}/discovery_results.json"
      delegate_to: localhost