# Copyright (c) 2020 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

---
- name: Rollback Layer-3 Migration (ACI)
  hosts: aci
  gather_facts: False
  tasks:
    - name: Import Migration Data
      include_vars:
        file: migration_data.yaml
        name: migration_data
    - name: Remove subnet from BD
      aci_bd_subnet:
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: "{{ item.tenant }}"
        bd: "{{ item.bd }}"
        subnet_name: "{{ item.name }}"
        gateway: "{{ item.gateway }}"
        mask: "{{ item.mask }}"
        scope: "{{ item.scope }}"
        state: absent
      delegate_to: localhost
      with_items: "{{ migration_data.aci.bd_subnet }}"
    - name: Change BDs to L2 Mode
      aci_bd:
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: "{{ item.tenant }}"
        vrf: "{{ item.l2_mode_settings.vrf }}"
        bd: "{{ item.name }}"
        mac_address: "{{ item.l2_mode_settings.mac }}"
        enable_routing: "{{ item.l2_mode_settings.enable_routing }}"
        arp_flooding: "{{ item.l2_mode_settings.arp_flooding }}"
        l2_unknown_unicast: "{{ item.l2_mode_settings.l2_unknown_unicast }}"
        l3_unknown_multicast: "{{ item.l2_mode_settings.l3_unknown_multicast }}"
        multi_dest: "{{ item.l2_mode_settings.multi_dest }}"
        state: present
      delegate_to: localhost
      with_items: "{{ migration_data.aci.bd }}"
    
- name: Rollback Layer-3 Migration (NXOS)
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Import Migration Data
      include_vars:
        file: migration_data.yaml
        name: migration_data
    - name: Enable VLAN in existing Network
      nxos_config:
        lines:
          - no shutdown
        parents: interface {{ item }}
        save_when: modified
      with_items: "{{ migration_data.legacy.l3_interface }}"
  
- name: Rollback Prepare Layer-3 Migration (ACI)
  hosts: aci
  gather_facts: False
  tasks:
    - name: Import Migration Data
      include_vars:
        file: migration_data.yaml
        name: migration_data
    - name: De-Associate BD to L3out(s)
      aci_bd_to_l3out:
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: "{{ item.tenant }}"
        bd: "{{ item.name }}"
        l3out: "{{ item.l3out }}"
        state: absent
      delegate_to: localhost
      with_items: "{{ migration_data.aci.bd_l3out }}"
    - name: Delete Contracts
      aci_contract:
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: "{{ item.tenant }}"
        contract: "{{ item.name }}"
        scope: "{{ item.scope }}"
        state: absent
      delegate_to: localhost
      with_items: "{{ migration_data.aci.contract }}"
    - name: Delete Contract Filters
      aci_filter:
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        tenant: "{{ item.tenant }}"
        filter: "{{ item.name }}"
        state: absent
      delegate_to: localhost
      with_items: "{{ migration_data.aci.contract_filter }}"
    - name: Delete Provide Contract by EPGs
      # Using the aci_rest module, as aci_epg_to_contract seems attempt removing epg
      aci_rest:  
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        path: /api/node/mo/uni/tn-{{ item.tenant }}/ap-{{ item.app_profile }}/epg-{{ item.name }}/rsprov-{{ item.contract}}.json
        method: post
        content:
          fvRsProv:
            attributes:
              dn: "uni/tn-{{ item.tenant }}/ap-{{ item.app_profile }}/epg-{{ item.name }}/rsprov-{{ item.contract }}"
              status: "deleted"
      delegate_to: localhost
      with_items: "{{ migration_data.aci.epg_contract }}"
    - name: Delete Consume Contracts by External EPG
      aci_rest:  
        host: '{{ inventory_hostname }}'
        username: '{{ apic_username }}'
        password: '{{ apic_password }}' 
        validate_certs: false
        path: /api/mo/uni/tn-{{ item.tenant }}/out-{{ item.l3out }}/instP-{{ item.name}}.json
        method: post
        content:
          fvRsCons:
            attributes:
              tnVzBrCPName: "{{ item.contract}}"
              status: "deleted"
      delegate_to: localhost
      with_items: "{{ migration_data.aci.ext_epg_contract }}"